"""Serializable route planner graph state for Phase 6D."""

from __future__ import annotations

import math
from collections.abc import Callable, Mapping, Sequence
from datetime import datetime
from numbers import Real
from typing import Any, Literal, NotRequired, TypedDict

from langgraph.graph import END, START, StateGraph
from route_corridor import DEFAULT_CORRIDOR_WIDTH_KM, RoutePolyline, filter_candidates_by_route_corridor
from stop_optimizer import (
    DEFAULT_MAX_RECOMMENDATIONS,
    StopCandidate,
    StopOptimizerInput,
    build_stop_optimizer_response,
    estimate_route_soc_summary,
)
from vehicle_profile import VehicleProfile, VehicleProfileError


GraphNodeName = Literal[
    "validate_route_request",
    "validate_vehicle_profile",
    "build_route_corridor",
    "find_station_candidates",
    "estimate_soc",
    "rank_charging_stops",
    "build_response",
]
FeaturePayload = dict[str, Any]
OptimizerPayload = dict[str, Any]
DEFAULT_ROUTE_ID = "route-request"
DEFAULT_ROUTE_PLANNER_RESPONSE_SOURCE = "local-dataset"
ROUTE_PLANNER_RESPONSE_LIMITATIONS: tuple[str, ...] = (
    "Route geometry is provided input, not generated by an external route API.",
    "No live traffic or weather is used.",
    "Availability and reliability use imported snapshot data, not live polling or historical uptime.",
    "Fallback recommendations may include unreachable or offline chargers and must be labeled clearly.",
)


class RoutePayload(TypedDict):
    distance_km: float
    polyline: list[list[float]]
    id: NotRequired[str]


class VehicleProfilePayload(TypedDict):
    battery_kwh: float
    current_soc: float
    target_arrival_soc: float
    consumption_kwh_per_km: float
    preferred_connector_types: list[str]
    max_charging_kw: float


class RoutePlannerConstraintsPayload(TypedDict, total=False):
    corridor_width_km: float
    max_results: int


class RouteCorridorPayload(TypedDict):
    polyline: list[list[float]]
    corridor_width_km: float


class RoutePlannerRequestPayload(TypedDict):
    route: RoutePayload
    vehicle: VehicleProfilePayload
    constraints: NotRequired[RoutePlannerConstraintsPayload]


class RoutePlannerErrorPayload(TypedDict):
    node: GraphNodeName
    message: str
    code: NotRequired[str]


class RoutePlannerGraphState(TypedDict, total=False):
    request: RoutePlannerRequestPayload
    route_id: str
    route_distance_km: float
    route_polyline: list[list[float]]
    route_corridor: RouteCorridorPayload
    vehicle: VehicleProfilePayload
    route_summary: OptimizerPayload
    constraints: RoutePlannerConstraintsPayload
    reference_time: str
    station_features: list[FeaturePayload]
    candidate_features: list[FeaturePayload]
    stop_candidates: list[OptimizerPayload]
    optimizer_input: OptimizerPayload
    optimizer_response: OptimizerPayload
    response: OptimizerPayload
    errors: list[RoutePlannerErrorPayload]


RoutePlannerNode = Callable[[RoutePlannerGraphState], RoutePlannerGraphState]


ROUTE_PLANNER_STATE_KEYS: tuple[str, ...] = (
    "request",
    "route_id",
    "route_distance_km",
    "route_polyline",
    "route_corridor",
    "vehicle",
    "route_summary",
    "constraints",
    "reference_time",
    "station_features",
    "candidate_features",
    "stop_candidates",
    "optimizer_input",
    "optimizer_response",
    "response",
    "errors",
)


def empty_route_planner_state() -> RoutePlannerGraphState:
    return {"errors": []}


def validate_route_request(state: RoutePlannerGraphState) -> RoutePlannerGraphState:
    errors = list(state.get("errors", []))
    request = state.get("request")
    if not isinstance(request, Mapping):
        return {"errors": [*errors, _route_request_error("request is required", "missing_request")]}

    route = request.get("route")
    if not isinstance(route, Mapping):
        return {"errors": [*errors, _route_request_error("request.route is required", "missing_route")]}

    try:
        route_id = _normalize_route_id(route.get("id"))
        route_distance_km = _validate_positive_number(route.get("distance_km"), "route.distance_km")
        route_polyline = _normalize_route_polyline(route.get("polyline"))
    except ValueError as exc:
        return {"errors": [*errors, _route_request_error(str(exc), "invalid_route")]}

    return {
        "route_id": route_id,
        "route_distance_km": route_distance_km,
        "route_polyline": route_polyline,
        "errors": errors,
    }


def validate_vehicle_profile(state: RoutePlannerGraphState) -> RoutePlannerGraphState:
    errors = list(state.get("errors", []))
    request = state.get("request")
    if not isinstance(request, Mapping):
        return {"errors": [*errors, _vehicle_profile_error("request is required", "missing_request")]}

    vehicle_payload = request.get("vehicle")
    if not isinstance(vehicle_payload, Mapping):
        return {"errors": [*errors, _vehicle_profile_error("request.vehicle is required", "missing_vehicle")]}

    try:
        vehicle = VehicleProfile(
            battery_kwh=vehicle_payload["battery_kwh"],
            current_soc=vehicle_payload["current_soc"],
            target_arrival_soc=vehicle_payload["target_arrival_soc"],
            consumption_kwh_per_km=vehicle_payload["consumption_kwh_per_km"],
            preferred_connector_types=vehicle_payload["preferred_connector_types"],
            max_charging_kw=vehicle_payload["max_charging_kw"],
        )
    except (KeyError, TypeError, VehicleProfileError) as exc:
        return {"errors": [*errors, _vehicle_profile_error(str(exc), "invalid_vehicle")]}

    return {"vehicle": vehicle.to_dict(), "errors": errors}


def build_route_corridor(state: RoutePlannerGraphState) -> RoutePlannerGraphState:
    errors = list(state.get("errors", []))
    try:
        if "route_polyline" not in state:
            raise ValueError("route_polyline is required")
        route_polyline = _normalize_route_polyline(state.get("route_polyline"))
        corridor_width_km = _route_corridor_width_from_state(state)
    except ValueError as exc:
        return {"errors": [*errors, _route_corridor_error(str(exc), "invalid_corridor")]}

    return {
        "constraints": {"corridor_width_km": corridor_width_km},
        "route_corridor": {
            "polyline": route_polyline,
            "corridor_width_km": corridor_width_km,
        },
        "errors": errors,
    }


def find_station_candidates(state: RoutePlannerGraphState) -> RoutePlannerGraphState:
    errors = list(state.get("errors", []))
    try:
        route_corridor = _route_corridor_from_state(state)
        station_features = _station_features_from_state(state)
        candidates = filter_candidates_by_route_corridor(
            station_features,
            _route_polyline_from_payload(route_corridor["polyline"]),
            route_corridor["corridor_width_km"],
            _route_total_distance_from_state(state),
        )
    except ValueError as exc:
        return {"errors": [*errors, _station_candidates_error(str(exc), "invalid_station_candidates")]}

    return {"candidate_features": candidates, "errors": errors}


def estimate_soc(state: RoutePlannerGraphState) -> RoutePlannerGraphState:
    errors = list(state.get("errors", []))
    try:
        route_distance_km = _validate_positive_number(state.get("route_distance_km"), "route_distance_km")
        vehicle = _vehicle_profile_from_state(state)
        summary = estimate_route_soc_summary(route_distance_km, vehicle)
    except (KeyError, TypeError, ValueError, VehicleProfileError) as exc:
        return {"errors": [*errors, _soc_estimate_error(str(exc), "invalid_soc_estimate")]}

    return {"route_summary": summary.to_dict(), "errors": errors}


def rank_charging_stops(state: RoutePlannerGraphState) -> RoutePlannerGraphState:
    errors = list(state.get("errors", []))
    try:
        route_id = _route_id_from_state(state)
        route_distance_km = _validate_positive_number(state.get("route_distance_km"), "route_distance_km")
        vehicle = _vehicle_profile_from_state(state)
        candidates = _stop_candidates_from_state(state)
        reference_time = _reference_time_from_state(state)
        optimizer_input = StopOptimizerInput(
            route_id=route_id,
            route_distance_km=route_distance_km,
            vehicle=vehicle,
            candidates=candidates,
            max_results=_max_results_from_state(state),
        )
        optimizer_response = build_stop_optimizer_response(optimizer_input, reference_time)
    except (KeyError, TypeError, ValueError, VehicleProfileError) as exc:
        return {"errors": [*errors, _stop_ranking_error(str(exc), "invalid_stop_ranking")]}

    return {
        "stop_candidates": [candidate.to_dict() for candidate in candidates],
        "optimizer_input": optimizer_input.to_dict(),
        "optimizer_response": optimizer_response.to_dict(),
        "errors": errors,
    }


def build_response(state: RoutePlannerGraphState) -> RoutePlannerGraphState:
    errors = list(state.get("errors", []))
    try:
        optimizer_response = _optimizer_response_from_state(state)
    except ValueError as exc:
        return {"errors": [*errors, _response_error(str(exc), "invalid_response")]}

    response = {
        **optimizer_response,
        "meta": _response_meta_from_state(state),
    }
    return {"response": response, "errors": errors}


ROUTE_PLANNER_GRAPH_NODES: tuple[tuple[GraphNodeName, RoutePlannerNode], ...] = (
    ("validate_route_request", validate_route_request),
    ("validate_vehicle_profile", validate_vehicle_profile),
    ("build_route_corridor", build_route_corridor),
    ("find_station_candidates", find_station_candidates),
    ("estimate_soc", estimate_soc),
    ("rank_charging_stops", rank_charging_stops),
    ("build_response", build_response),
)


def build_route_planner_graph() -> Any:
    graph = StateGraph(RoutePlannerGraphState)
    for node_name, node in ROUTE_PLANNER_GRAPH_NODES:
        graph.add_node(node_name, node)

    graph.add_edge(START, ROUTE_PLANNER_GRAPH_NODES[0][0])
    for (node_name, _), (next_node_name, _) in zip(ROUTE_PLANNER_GRAPH_NODES, ROUTE_PLANNER_GRAPH_NODES[1:]):
        graph.add_edge(node_name, next_node_name)
    graph.add_edge(ROUTE_PLANNER_GRAPH_NODES[-1][0], END)
    return graph.compile()


def _route_request_error(message: str, code: str) -> RoutePlannerErrorPayload:
    return {"node": "validate_route_request", "message": message, "code": code}


def _vehicle_profile_error(message: str, code: str) -> RoutePlannerErrorPayload:
    return {"node": "validate_vehicle_profile", "message": message, "code": code}


def _route_corridor_error(message: str, code: str) -> RoutePlannerErrorPayload:
    return {"node": "build_route_corridor", "message": message, "code": code}


def _station_candidates_error(message: str, code: str) -> RoutePlannerErrorPayload:
    return {"node": "find_station_candidates", "message": message, "code": code}


def _soc_estimate_error(message: str, code: str) -> RoutePlannerErrorPayload:
    return {"node": "estimate_soc", "message": message, "code": code}


def _stop_ranking_error(message: str, code: str) -> RoutePlannerErrorPayload:
    return {"node": "rank_charging_stops", "message": message, "code": code}


def _response_error(message: str, code: str) -> RoutePlannerErrorPayload:
    return {"node": "build_response", "message": message, "code": code}


def _normalize_route_id(value: object) -> str:
    if value is None:
        return DEFAULT_ROUTE_ID
    if not isinstance(value, str):
        raise ValueError("route.id must be a string")
    normalized = value.strip()
    return normalized or DEFAULT_ROUTE_ID


def _validate_positive_number(value: object, field: str) -> float:
    if isinstance(value, bool) or not isinstance(value, Real):
        raise ValueError(f"{field} must be a number")
    number = float(value)
    if not math.isfinite(number) or number <= 0:
        raise ValueError(f"{field} must be positive")
    return number


def _validate_positive_integer(value: object, field: str) -> int:
    if isinstance(value, bool) or not isinstance(value, int):
        raise ValueError(f"{field} must be a positive integer")
    if value <= 0:
        raise ValueError(f"{field} must be a positive integer")
    return value


def _validate_non_negative_number(value: object, field: str) -> float:
    if isinstance(value, bool) or not isinstance(value, Real):
        raise ValueError(f"{field} must be a number")
    number = float(value)
    if not math.isfinite(number) or number < 0:
        raise ValueError(f"{field} must be non-negative")
    return number


def _route_id_from_state(state: RoutePlannerGraphState) -> str:
    route_id = state.get("route_id")
    if not isinstance(route_id, str) or not route_id.strip():
        raise ValueError("route_id is required")
    return route_id.strip()


def _route_corridor_width_from_state(state: RoutePlannerGraphState) -> float:
    request = state.get("request")
    if not isinstance(request, Mapping):
        return DEFAULT_CORRIDOR_WIDTH_KM

    constraints = request.get("constraints")
    if constraints is None:
        return DEFAULT_CORRIDOR_WIDTH_KM
    if not isinstance(constraints, Mapping):
        raise ValueError("request.constraints must be an object")

    return _validate_non_negative_number(
        constraints.get("corridor_width_km", DEFAULT_CORRIDOR_WIDTH_KM),
        "constraints.corridor_width_km",
    )


def _route_corridor_from_state(state: RoutePlannerGraphState) -> RouteCorridorPayload:
    corridor = state.get("route_corridor")
    if not isinstance(corridor, Mapping):
        raise ValueError("route_corridor is required")

    return {
        "polyline": _normalize_route_polyline(corridor.get("polyline")),
        "corridor_width_km": _validate_non_negative_number(
            corridor.get("corridor_width_km"),
            "route_corridor.corridor_width_km",
        ),
    }


def _route_total_distance_from_state(state: RoutePlannerGraphState) -> float | None:
    value = state.get("route_distance_km")
    if value is None:
        return None
    return _validate_positive_number(value, "route_distance_km")


def _station_features_from_state(state: RoutePlannerGraphState) -> list[FeaturePayload]:
    features = state.get("station_features")
    if isinstance(features, (str, bytes)) or not isinstance(features, Sequence):
        raise ValueError("station_features is required")

    normalized: list[FeaturePayload] = []
    for index, feature in enumerate(features):
        if not isinstance(feature, Mapping):
            raise ValueError(f"station_features[{index}] must be an object")
        normalized.append(dict(feature))
    return normalized


def _vehicle_profile_from_state(state: RoutePlannerGraphState) -> VehicleProfile:
    vehicle_payload = state.get("vehicle")
    if not isinstance(vehicle_payload, Mapping):
        raise ValueError("vehicle is required")

    return VehicleProfile(
        battery_kwh=vehicle_payload["battery_kwh"],
        current_soc=vehicle_payload["current_soc"],
        target_arrival_soc=vehicle_payload["target_arrival_soc"],
        consumption_kwh_per_km=vehicle_payload["consumption_kwh_per_km"],
        preferred_connector_types=vehicle_payload["preferred_connector_types"],
        max_charging_kw=vehicle_payload["max_charging_kw"],
    )


def _stop_candidates_from_state(state: RoutePlannerGraphState) -> tuple[StopCandidate, ...]:
    candidate_features = state.get("candidate_features")
    if isinstance(candidate_features, (str, bytes)) or not isinstance(candidate_features, Sequence):
        raise ValueError("candidate_features is required")
    if len(candidate_features) == 0:
        raise ValueError("candidate_features must include at least one candidate")

    return tuple(_stop_candidate_from_feature(feature, index) for index, feature in enumerate(candidate_features))


def _stop_candidate_from_feature(feature: object, index: int) -> StopCandidate:
    if not isinstance(feature, Mapping):
        raise ValueError(f"candidate_features[{index}] must be an object")

    properties = feature.get("properties")
    if not isinstance(properties, Mapping):
        raise ValueError(f"candidate_features[{index}].properties is required")

    return StopCandidate(
        station_id=_required_text_property(
            properties,
            f"candidate_features[{index}].properties.station_id",
            "station_id",
            "charger_id",
        ),
        name=_required_text_property(
            properties,
            f"candidate_features[{index}].properties.name",
            "name",
            "charger_name",
        ),
        connector_type=_required_text_property(
            properties,
            f"candidate_features[{index}].properties.connector_type",
            "connector_type",
        ),
        max_kw=_validate_positive_number(
            properties.get("max_kw"),
            f"candidate_features[{index}].properties.max_kw",
        ),
        distance_from_route_km=_validate_non_negative_number(
            properties.get("distance_from_route_km"),
            f"candidate_features[{index}].properties.distance_from_route_km",
        ),
        route_distance_km=_validate_non_negative_number(
            properties.get("route_distance_km"),
            f"candidate_features[{index}].properties.route_distance_km",
        ),
        status=_availability_status_from_properties(properties, index),
        status_updated_at=_optional_text_property(
            properties.get("status_updated_at"),
            f"candidate_features[{index}].properties.status_updated_at",
        ),
    )


def _required_text_property(properties: Mapping[str, Any], field: str, *keys: str) -> str:
    for key in keys:
        value = properties.get(key)
        if isinstance(value, str) and value.strip():
            return value.strip()
    raise ValueError(f"{field} is required")


def _optional_text_property(value: object, field: str) -> str | None:
    if value is None:
        return None
    if not isinstance(value, str):
        raise ValueError(f"{field} must be a string")
    normalized = value.strip()
    return normalized or None


def _availability_status_from_properties(properties: Mapping[str, Any], index: int) -> str:
    value = properties.get("status", "unknown")
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"candidate_features[{index}].properties.status must be a string")
    return value.strip()


def _reference_time_from_state(state: RoutePlannerGraphState) -> datetime:
    value = state.get("reference_time")
    if not isinstance(value, str) or not value.strip():
        raise ValueError("reference_time is required")

    try:
        reference_time = datetime.fromisoformat(value.strip())
    except ValueError as exc:
        raise ValueError("reference_time must be an ISO 8601 datetime") from exc

    if reference_time.tzinfo is None or reference_time.utcoffset() is None:
        raise ValueError("reference_time must include timezone")
    return reference_time


def _max_results_from_state(state: RoutePlannerGraphState) -> int:
    constraints = state.get("constraints")
    if constraints is not None and not isinstance(constraints, Mapping):
        raise ValueError("constraints must be an object")
    if isinstance(constraints, Mapping) and "max_results" in constraints:
        return _validate_positive_integer(constraints.get("max_results"), "constraints.max_results")

    request = state.get("request")
    if isinstance(request, Mapping):
        request_constraints = request.get("constraints")
        if request_constraints is not None and not isinstance(request_constraints, Mapping):
            raise ValueError("request.constraints must be an object")
        if isinstance(request_constraints, Mapping) and "max_results" in request_constraints:
            return _validate_positive_integer(
                request_constraints.get("max_results"),
                "constraints.max_results",
            )

    return DEFAULT_MAX_RECOMMENDATIONS


def _optimizer_response_from_state(state: RoutePlannerGraphState) -> OptimizerPayload:
    optimizer_response = state.get("optimizer_response")
    if not isinstance(optimizer_response, Mapping):
        raise ValueError("optimizer_response is required")

    response = dict(optimizer_response)
    route_id = response.get("route_id")
    if not isinstance(route_id, str) or not route_id.strip():
        raise ValueError("optimizer_response.route_id is required")
    response["route_id"] = route_id.strip()

    summary = response.get("summary")
    if not isinstance(summary, Mapping):
        raise ValueError("optimizer_response.summary is required")
    response["summary"] = dict(summary)

    recommendations = response.get("recommendations")
    if isinstance(recommendations, (str, bytes)) or not isinstance(recommendations, Sequence):
        raise ValueError("optimizer_response.recommendations must be a list")
    response["recommendations"] = [
        _recommendation_payload_from_response(recommendation, index)
        for index, recommendation in enumerate(recommendations)
    ]
    return response


def _recommendation_payload_from_response(value: object, index: int) -> OptimizerPayload:
    if not isinstance(value, Mapping):
        raise ValueError(f"optimizer_response.recommendations[{index}] must be an object")
    return dict(value)


def _response_meta_from_state(state: RoutePlannerGraphState) -> OptimizerPayload:
    meta: OptimizerPayload = {
        "source": _response_source_from_state(state),
        "limitations": list(ROUTE_PLANNER_RESPONSE_LIMITATIONS),
    }

    snapshot_date = _candidate_metadata_text_from_state(state, "snapshot_date")
    if snapshot_date is not None:
        meta["snapshot_date"] = snapshot_date

    freshness_label = _freshness_label_from_optimizer_response(state)
    if freshness_label is not None:
        meta["freshness_label"] = freshness_label

    return meta


def _response_source_from_state(state: RoutePlannerGraphState) -> str:
    return _candidate_metadata_text_from_state(state, "source") or DEFAULT_ROUTE_PLANNER_RESPONSE_SOURCE


def _candidate_metadata_text_from_state(state: RoutePlannerGraphState, key: str) -> str | None:
    for features_key in ("candidate_features", "station_features"):
        features = state.get(features_key)
        if isinstance(features, (str, bytes)) or not isinstance(features, Sequence):
            continue
        for feature in features:
            if not isinstance(feature, Mapping):
                continue
            properties = feature.get("properties")
            if not isinstance(properties, Mapping):
                continue
            value = properties.get(key)
            if isinstance(value, str) and value.strip():
                return value.strip()
    return None


def _freshness_label_from_optimizer_response(state: RoutePlannerGraphState) -> str | None:
    optimizer_response = state.get("optimizer_response")
    if not isinstance(optimizer_response, Mapping):
        return None

    recommendations = optimizer_response.get("recommendations")
    if isinstance(recommendations, (str, bytes)) or not isinstance(recommendations, Sequence):
        return None

    for recommendation in recommendations:
        if not isinstance(recommendation, Mapping):
            continue
        reasons = recommendation.get("reasons")
        if isinstance(reasons, (str, bytes)) or not isinstance(reasons, Sequence):
            continue
        label = _freshness_label_from_reasons(reasons)
        if label is not None:
            return label
    return None


def _freshness_label_from_reasons(reasons: Sequence[object]) -> str | None:
    if "fresh_availability" in reasons:
        return "fresh"
    if "aging_availability" in reasons:
        return "aging"
    if "stale_availability_penalty" in reasons:
        return "stale"
    if "unknown_availability_penalty" in reasons:
        return "unknown"
    return None


def _route_polyline_from_payload(polyline: list[list[float]]) -> RoutePolyline:
    return tuple((point[0], point[1]) for point in polyline)


def _normalize_route_polyline(value: object) -> list[list[float]]:
    if isinstance(value, (str, bytes)) or not isinstance(value, Sequence):
        raise ValueError("route.polyline must be a coordinate list")
    if len(value) < 2:
        raise ValueError("route.polyline must contain at least two points")

    return [_normalize_route_coordinate(point, index) for index, point in enumerate(value)]


def _normalize_route_coordinate(value: object, index: int) -> list[float]:
    if isinstance(value, (str, bytes)) or not isinstance(value, Sequence) or len(value) != 2:
        raise ValueError(f"route.polyline[{index}] must be [lon, lat]")

    lon = _validate_coordinate_number(value[0], f"route.polyline[{index}][0]")
    lat = _validate_coordinate_number(value[1], f"route.polyline[{index}][1]")
    if not -180 <= lon <= 180:
        raise ValueError(f"route.polyline[{index}][0] must be between -180 and 180")
    if not -90 <= lat <= 90:
        raise ValueError(f"route.polyline[{index}][1] must be between -90 and 90")
    return [lon, lat]


def _validate_coordinate_number(value: object, field: str) -> float:
    if isinstance(value, bool) or not isinstance(value, Real):
        raise ValueError(f"{field} must be a number")
    number = float(value)
    if not math.isfinite(number):
        raise ValueError(f"{field} must be finite")
    return number
