import { describe, expect, it } from 'vitest';
import {
  formatRoutePlannerReason,
  formatRoutePlannerScore,
  formatRoutePlannerSoc,
  getRoutePlannerLimitations,
  getRoutePlannerMetaRows,
  getRoutePlannerErrorMessages,
  hasFallbackReason,
} from './routePlannerDisplay';
import { RoutePlannerApiError } from './routePlanner';

describe('formatRoutePlannerReason', () => {
  it('maps supported backend reason codes to display labels', () => {
    expect(formatRoutePlannerReason('connector_match')).toBe('Connector match');
    expect(formatRoutePlannerReason('stale_availability_penalty')).toBe('Stale availability');
    expect(formatRoutePlannerReason('offline_fallback')).toBe('Offline fallback');
  });

  it('keeps unknown backend reason codes visible without inventing details', () => {
    expect(formatRoutePlannerReason('new_backend_reason')).toBe('new backend reason');
  });
});

describe('hasFallbackReason', () => {
  it('detects fallback recommendation reasons', () => {
    expect(hasFallbackReason(['reachable', 'offline_fallback'])).toBe(true);
    expect(hasFallbackReason(['reachable', 'fresh_availability'])).toBe(false);
  });
});

describe('route planner number formatting', () => {
  it('formats score and state of charge values for compact rows', () => {
    expect(formatRoutePlannerScore(0.914)).toBe('0.91');
    expect(formatRoutePlannerSoc(0.537)).toBe('54%');
  });
});

describe('route planner metadata formatting', () => {
  it('keeps every backend limitation in order', () => {
    const limitations = [
      'Route geometry is provided input, not generated by an external route API.',
      'No live traffic or weather is used.',
      'Availability uses imported snapshot data.',
      'Fallback recommendations must be labeled clearly.',
    ];

    expect(getRoutePlannerLimitations({ source: 'local-dataset', limitations })).toEqual(limitations);
  });

  it('returns only present metadata rows', () => {
    expect(
      getRoutePlannerMetaRows({
        source: 'local-dataset',
        freshness_label: 'fresh',
        snapshot_date: '2026-05-19',
        limitations: [],
      }),
    ).toEqual([
      ['Source', 'local-dataset'],
      ['Freshness', 'fresh'],
      ['Snapshot', '2026-05-19'],
    ]);

    expect(getRoutePlannerMetaRows({ source: 'local-dataset', limitations: [] })).toEqual([
      ['Source', 'local-dataset'],
    ]);
  });
});

describe('getRoutePlannerErrorMessages', () => {
  it('formats backend graph validation errors with node and code', () => {
    const error = new RoutePlannerApiError(400, [
      { node: 'validate_route_request', message: 'request.route is required', code: 'missing_route' },
    ]);

    expect(getRoutePlannerErrorMessages(error)).toEqual([
      'validate_route_request / missing_route: request.route is required',
    ]);
  });

  it('keeps string backend error details visible', () => {
    expect(getRoutePlannerErrorMessages(new RoutePlannerApiError(500, 'Synthetic station fixture not found'))).toEqual([
      'Synthetic station fixture not found',
    ]);
  });
});
